services:
  mysql:
    # image: mysql:8.4
    build: ./database/
    restart: unless-stopped
    env_file:
      - ./../.env
    ports:
      - '3306:3306'
    volumes:
      - database-volume:/var/lib/mysql:z
      # - ./database/initdb:/docker-entrypoint-initdb.d:z
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  database-volume:
    driver: local 